# Generated by Django 4.1.7 on 2023-03-15 08:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 9, 31, 59, 859961))),
                ('number_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
